classDiagram
  class Account {
    accountName: String
    accountNumber: String
    bankName: String
    status: String
    organizationId: ObjectId [Required]
    createdAt: Date
    updatedAt: Date
  }

  Account --> Organization
