classDiagram
  class Attachment {
    uploader: ObjectId
    fileLink: String
    organizationId: ObjectId [Required]
    createdAt: Date
    updatedAt: Date
  }

  Attachment --> employee
  Attachment --> organization
