classDiagram
  class Comment {
    text: String
    author: ObjectId
    organizationId: ObjectId [Required]
    createdAt: Date
    updatedAt: Date
  }

  Comment --> Employee
  Comment --> Organization
