classDiagram
  class Department {
    name: String [Required]
    description: String
    members: Array
    deleted: Boolean
    organizationId: ObjectId [Required]
    createdAt: Date
    updatedAt: Date
  }

  Department --> organization
