classDiagram
    %% Model Relationships

    class Account
    class AccountCode
    class BankDetail
    class Benefit
    class BudgetCode
    class Calendar
    class Comment
    class Contract
    class Department
    class Employee
    class ExitManagement
    class Guarantor
    class KanbanColumn
    class KanbanTemplate
    class Leave
    class LeaveType
    class MaritalDetail
    class NextOfKin
    class Notification
    class Organization
    class PaySchedule
    class Payslip
    class PerformanceManagement
    class Permission
    class PersonalInformation
    class Project
    class ProjectFunder
    class Qualification
    class RefreshToken
    class Requisition
    class Task
    class Team
    class TimeSheet
    class Vendor
